version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3333:3333"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./usr/local/var/mongodb:/data/db
    ports:
      - "27017:27017"