version: "3"
services:
  app:
    container_name: app
    build: .
    env_file: ./.env
    ports:
      - "${PORT_MACHINE}:3222"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"